### ISSUE TITLE
Failed to Execute Script Main

### ISSUE THREAD

**Issue by Merith-TK** [darenliang/dsgui#2]
![image](https://user-images.githubusercontent.com/10422110/127787192-da019292-fb42-40c3-a99d-c2495299f036.png)

**Comment by darenliang** [comment]
Sorry about that,

One of the python files was weirdly formatted and prevented the application from starting. The latest release should fix that.

**Comment by Merith-TK** [comment]
Oky!

**Comment by Merith-TK** [comment]
Yeap that fixed it!
